# -*- coding: utf-8 -*-
"""Access specifier

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12MVbWDpV6X1n1l9ZvBIbrKIJ4DUPRrOv
"""

# ACCESS SPECIFIERS
class student:
  def __init__(self, name , branch, score, result):
       self. name = name
       self._branch = branch
       self.__score = score
       self.__result = result
  def showname(self):
       print(self.name)
  def _showbranch(self):
       print(self._branch)
  def _showscore(self):
       print(self.__score)
  def _showresult(self):
      print(self.__result)
a = student("anjali", "MCA", 90, "passed")
a.showname()
a._showbranch()
a._showscore()
a._showresult()